project:
	g++ -o ./bin/proj1 main.cpp
tests: 
	g++ -o ./bin/test1 ./testSrc/test1.cpp
	g++ -o ./bin/test2 ./testSrc/test2.cpp
	g++ -o ./bin/test3 ./testSrc/test3.cpp
	g++ -o ./bin/test4 ./testSrc/test4.cpp
	g++ -o ./bin/test5 ./testSrc/test5.cpp
